### ISSUE TITLE
URI is missing ')' from typography.sass

### ISSUE THREAD

**Issue by juliancoleman** [juliancoleman/Material#1]
Harp is providing the following error:

    Sass -> CSS (URI is missing ')' ) ../lib/typography.sass

**Comment by juliancoleman** [comment]
This was an issue with the Google fonts URI. Harp doesn't like these for some reason.

**Comment by xDarkicex** [comment]
Must be why its compiled on my end

**Comment by juliancoleman** [comment]
There seems to be a bus issue in Harp that determines the `//` in the URI to be an expected inline comment. Moved the fonts to a Jade file instead and noted that typography.sass depends on typography.jade. This has solved the issue. Typography.sass has color.sass imported by default now. Missing color.sass in the `@import` will result in an error being thrown.
